### PR TITLE
[SEM-051]:ENLACE VARIABLE(UBICACION / SIGUENOS)

### PR DESCRIPTION
**Pull request by JOSELEOND**
Como usuario quiero ver enlaces sobre nuestra ubicacion ademas de poder acceder a nuestra pagina de facebook.

### CODE REVIEW

**Review by Ditmar — CHANGES_REQUESTED** [review]
Please rebase your branch

**Comment by DanX3N0** [comment]
the component is in atoms, but in storybook this display in molecules section:
image
image

fix it

**Comment by DanX3N0** [comment]
is an atom, should be a single element with varations:
image

by example:
variation 1)
image
variation 2)
image

**Comment by DanX3N0** [comment]
pr: 
image
image
image
image

it's ok

**Review by Ditmar — APPROVED** [review]

**Pull request merged**
