### PR TITLE
[SEM - 316]: Refactor, isolar los estilos de los componentes SEM-067 & SEM-068

### PR DESCRIPTION
**Pull request by DanielaAlejandraMamaniSilva**

### CODE REVIEW

**Comment by DanielaAlejandraMamaniSilva** [comment]
Screenshot_20240627-101216_1
Screenshot_20240627-101212_1
Screenshot_20240627-101149
Screenshot_20240627-101200_1

**Review by Ditmar — APPROVED** [review]

**Comment by Ditmar** [comment]
please make a rebase of your branch

**Comment by DanielaAlejandraMamaniSilva** [comment]
rebased
image

**Review by Ditmar — CHANGES_REQUESTED** [review]
NO HICISTE UN SIMPLE REBASE

**Review by Ditmar — APPROVED** [review]

**Comment by Ditmar** [comment]
image
hey this branch couldn't merge  because there a several conflicts with the pr, why you don't make the rebase

**Review by Ditmar — APPROVED** [review]

**Review by Ditmar — APPROVED** [review]

**Pull request merged**
